frutos_user:
    resource: "@FrutosUserBundle/Controller/"
    type:     annotation
    prefix:   /user

frutos_main:
    resource: "@FrutosMainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@FrutosMainBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group