frutos_main:
    resource: "@FrutosMainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@FrutosMainBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"